### ISSUE TITLE
TypeError: Object Variable has no method 'codePointAt'

### ISSUE THREAD

**Issue by bluurn** [denysdovhan/bash-handbook#14]
Hello, just installed bash-handbook@1.2.2 and run into the following issue when tried to run `bash-handbook`:

```
/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:312
        var code = str.codePointAt(i);
                       ^
TypeError: Object Variable has no method 'codePointAt'
    at getStringWidth (/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:312:24)
    at /usr/lib/node_modules/bash-handbook/node_modules/msee/node_modules/text-table/index.js:33:21
    at Array.forEach (native)
    at forEach (/usr/lib/node_modules/bash-handbook/node_modules/msee/node_modules/text-table/index.js:73:31)
    at /usr/lib/node_modules/bash-handbook/node_modules/msee/node_modules/text-table/index.js:32:9
    at Array.reduce (native)
    at reduce (/usr/lib/node_modules/bash-handbook/node_modules/msee/node_modules/text-table/index.js:63:30)
    at module.exports (/usr/lib/node_modules/bash-handbook/node_modules/msee/node_modules/text-table/index.js:31:17)
    at tableFormat (/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:294:12)
    at processToken (/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:188:23)

```

Please let me know how can I resolve this issue.

Thank you.

**Comment by denysdovhan** [comment]
Can't reproduce this bug. Seems like it's a trouble with [msee](https://github.com/firede/msee).

**Comment by denysdovhan** [comment]
I have reported and issue to [msee#32](https://github.com/firede/msee/issues/32).

**Comment by bucaran** [comment]
Hi @bluurn Can you try again? It should be solved now.

**Comment by TerkaSlan** [comment]
Hi, I ran into the same issue (with the same error message as above) today after installing `bash-handbook`. Moreover, I'm unable to type anything to the terminal afterwards.
I'm running `npm 1.3.6`. 

Thanks in advance for looking at it again.

**Comment by bucaran** [comment]
Any reason I am on the bleeding edge at `3.7`, but anything before 1.4 we are talking about almost 2 years ago. Any reason you don't want to upgrade your `npm`?

**Comment by TerkaSlan** [comment]
Apologies, I don't use `npm` very often and didn't realize I was that far in the past with that version.
I upgraded to `3.6.0`, however, the issue still persists:
```
/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:312
        var code = str.codePointAt(i);
                       ^
TypeError: Object Variable has no method 'codePointAt'
    at getStringWidth (/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:312:24)
    at /usr/lib/node_modules/bash-handbook/node_modules/text-table/index.js:33:21
    at Array.forEach (native)
    at forEach (/usr/lib/node_modules/bash-handbook/node_modules/text-table/index.js:73:31)
    at /usr/lib/node_modules/bash-handbook/node_modules/text-table/index.js:32:9
    at Array.reduce (native)
    at reduce (/usr/lib/node_modules/bash-handbook/node_modules/text-table/index.js:63:30)
    at module.exports (/usr/lib/node_modules/bash-handbook/node_modules/text-table/index.js:31:17)
    at tableFormat (/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:294:12)
    at processToken (/usr/lib/node_modules/bash-handbook/node_modules/msee/lib/msee.js:188:23)
```

**Comment by bucaran** [comment]
@TerkaSlan Sorry for the trouble! Then, the problem is `msee`'s new version still hasn't been published.

/cc @martinheidegger or @firede

**Comment by denysdovhan** [comment]
> Published 0.4.0 - please review :)
> — https://github.com/firede/msee/issues/32#issuecomment-177470375

@TerkaSlan @bluurn check it out.

**Comment by TerkaSlan** [comment]
I uninstalled `bash-handbook` and installed it again, installed `msee`, no change for me, I'm still getting the same error.

**Comment by bluurn** [comment]
Just found the problem.

I have used system nodejs v0.10.37, when I tried to use v5.5.0, this issue dissappeared.

@TerkaSlan please check it.

**Comment by denysdovhan** [comment]
@bluurn just for future: always use the latest stable release on your machines. LTS releases are for production environment.

**Comment by TerkaSlan** [comment]
Thanks @bluurn , I previously had `nodejs v0.10.36`, I updated to `v5.5.0` and everything works perfectly, the issue is gone.

**Comment by denysdovhan** [comment]
Awesome! I'm gonna close this issue.
